"""
tools/mkdocs_builder.py

Builds a complete MkDocs site from the generated documentation.

After DocWriter creates the .md files, this module:
1. Generates mkdocs.yml with Material theme + Mermaid support
2. Builds the navigation tree from the actual generated files
3. Writes a custom CSS overrides file for a professional look
4. Optionally runs `mkdocs build` to create the static HTML site

The output is a self-contained `site/` folder you can:
  - Open locally (just open site/index.html)
  - Push to GitHub Pages
  - Deploy to any static hosting (Netlify, Vercel, S3)
"""
import subprocess
import logging
import shutil
from pathlib import Path
from datetime import datetime

logger = logging.getLogger(__name__)


MKDOCS_YML_TEMPLATE = """\
# ============================================================
# MkDocs Configuration — Salesforce LOS Documentation
# Generated by SF LOS Documentation Agent on {generated_at}
# ============================================================

site_name: "{org_name} — LOS Documentation"
site_description: "Auto-generated documentation for the Salesforce Loan Origination System"
site_author: "SF LOS Documentation Agent"
docs_dir: docs
site_dir: site

# ── Theme ────────────────────────────────────────────────────
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs              # Top-level tabs
    - navigation.tabs.sticky       # Tabs stay visible on scroll
    - navigation.sections          # Group sub-sections
    - navigation.expand            # Auto-expand active section
    - navigation.path              # Breadcrumb path
    - navigation.top               # Back-to-top button
    - search.highlight             # Highlight search results
    - search.suggest               # Search auto-complete
    - content.code.copy            # Copy button on code blocks
    - content.code.annotate        # Code annotations
  icon:
    repo: fontawesome/brands/github

# ── Extensions ───────────────────────────────────────────────
markdown_extensions:
  - admonition                     # !!! note / warning / tip callouts
  - pymdownx.details               # Collapsible callouts
  - pymdownx.superfences:          # Code fences + Mermaid diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:               # Tabbed content
      alternate_style: true
  - pymdownx.highlight:            # Syntax highlighting
      anchor_linenums: true
  - pymdownx.inlinehilite          # Inline code highlighting
  - tables                         # Markdown tables
  - toc:                           # Table of contents
      permalink: true
      toc_depth: 3
  - attr_list                      # HTML attributes on elements
  - md_in_html                     # Markdown inside HTML blocks

# ── Plugins ──────────────────────────────────────────────────
plugins:
  - search:
      lang: en
  - tags                           # Tag pages

# ── Extra ────────────────────────────────────────────────────
extra:
  generator: false                 # Remove "Made with MkDocs" footer
  social:
    - icon: fontawesome/solid/building-columns
      link: "#"
      name: Internal Documentation

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/mermaid-init.js         # Initialize Mermaid diagrams

# ── Navigation ───────────────────────────────────────────────
{nav_section}
"""

MERMAID_INIT_JS = """\
// Initialize Mermaid for MkDocs Material theme
document$.subscribe(() => {
  if (typeof mermaid !== 'undefined') {
    mermaid.initialize({
      startOnLoad: true,
      theme: document.body.getAttribute('data-md-color-scheme') === 'slate' ? 'dark' : 'default',
      flowchart: { useMaxWidth: true, htmlLabels: true },
    });
  }
});
"""

EXTRA_CSS = """\
/* SF LOS Documentation — Custom Styles */

/* Hero banner on index page */
.md-typeset h1:first-child {
  font-size: 2rem;
  border-bottom: 3px solid var(--md-primary-fg-color);
  padding-bottom: 0.5rem;
  margin-bottom: 1.5rem;
}

/* Make component API names stand out */
code {
  background-color: var(--md-code-bg-color);
  border-radius: 3px;
  font-weight: 500;
}

/* Hidden rules callout — golden highlight */
.md-typeset blockquote {
  border-left: 4px solid #f5a623;
  background: rgba(245, 166, 35, 0.06);
}

/* Stage badges in tables */
.md-typeset table th {
  background-color: var(--md-primary-fg-color--dark);
  color: white;
}

/* Risk severity colors */
.md-typeset .risk-high  { color: #c0392b; font-weight: 700; }
.md-typeset .risk-med   { color: #d68910; font-weight: 700; }
.md-typeset .risk-low   { color: #27ae60; }

/* Full-width Mermaid diagrams */
.mermaid svg {
  max-width: 100% !important;
  height: auto;
}

/* Component metadata cards */
.md-typeset details {
  border-radius: 6px;
}
"""

INDEX_MD_TEMPLATE = """\
# {org_name} — Loan Origination System

!!! info "Auto-Generated Documentation"
    Generated by the **SF LOS Documentation Agent** on `{generated_at}`.  
    This documentation was reverse-engineered from your Salesforce org's metadata using AI.

---

## Quick Navigation

<div class="grid cards" markdown>

-   :material-map: **[Loan Journey Overview](journey/overview.md)**

    The complete end-to-end narrative — from lead capture to disbursement.

-   :material-lightning-bolt: **[Hidden Rules Discovered](reference/hidden-rules.md)**

    Business logic found in code that was never written down. Start here.

-   :material-api: **[Integration Inventory](reference/integrations.md)**

    Every external system your LOS connects to.

-   :material-shield-alert: **[Risk Register](reference/risk-register.md)**

    Technical debt and risk flags for engineering review.

</div>

---

## Coverage Summary

| Metric | Count |
|--------|-------|
| Total components analyzed | **{total_components}** |
| Loan journey stages documented | **{stage_count}** |
| Hidden business rules discovered | **{hidden_rules_count}** |
| External integrations found | **{integration_count}** |
| Risk flags surfaced | **{risk_count}** |

---

## Loan Journey at a Glance

```mermaid
flowchart LR
    L[Lead Capture] --> A[Application]
    A --> D[Documents]
    D --> K[KYC & Bureau]
    K --> U[Underwriting]
    U --> C[Credit Decision]
    C --> S[Sanctioning]
    S --> G[Legal Docs]
    G --> B[Disbursement]
    B --> P[Post-Disbursal]

    style L fill:#4CAF50,color:white
    style C fill:#FF9800,color:white
    style B fill:#2196F3,color:white
    style P fill:#9C27B0,color:white
```

---

## How to Use This Documentation

1. **Start with the [Loan Journey Overview](journey/overview.md)** — understand the big picture
2. **Read [Hidden Rules](reference/hidden-rules.md)** — validate AI findings with your business team
3. **Browse by stage** — each stage folder has a component list and diagram
4. **Use search** — press `/` or `S` to search across all documentation
"""


class MkDocsBuilder:
    """
    Builds a complete MkDocs site from generated Markdown documentation.
    """

    def __init__(self, docs_dir: str, org_name: str = "Salesforce LOS"):
        self.docs_dir = Path(docs_dir)
        self.site_root = self.docs_dir.parent  # parent of docs/ folder
        self.org_name = org_name
        self.generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    def build(self, journey) -> Path:
        """
        Full build: generate mkdocs.yml, assets, index, then run mkdocs build.
        Returns the path to the generated site/ directory.
        """
        logger.info("Building MkDocs site...")

        # 1. Create assets directory
        assets_dir = self.docs_dir / "assets"
        assets_dir.mkdir(exist_ok=True)
        (assets_dir / "mermaid-init.js").write_text(MERMAID_INIT_JS)
        (assets_dir / "extra.css").write_text(EXTRA_CSS)
        logger.info("  Created assets (CSS + JS)")

        # 2. Embed Mermaid diagrams into stage docs
        self._embed_mermaid_diagrams()

        # 3. Generate navigation tree
        nav_section = self._build_nav(journey)

        # 4. Write mkdocs.yml
        mkdocs_yml_path = self.site_root / "mkdocs.yml"
        mkdocs_yml = MKDOCS_YML_TEMPLATE.format(
            generated_at=self.generated_at,
            org_name=self.org_name,
            nav_section=nav_section,
        )
        mkdocs_yml_path.write_text(mkdocs_yml)
        logger.info(f"  Wrote mkdocs.yml → {mkdocs_yml_path}")

        # 5. Write index page
        index_path = self.docs_dir / "index.md"
        index_content = INDEX_MD_TEMPLATE.format(
            org_name=self.org_name,
            generated_at=self.generated_at,
            total_components=journey.total_components,
            stage_count=sum(1 for s in journey.stages if s.components),
            hidden_rules_count=len(journey.hidden_rules_master),
            integration_count=len(journey.integration_inventory),
            risk_count=len(journey.risk_register),
        )
        index_path.write_text(index_content)
        logger.info("  Wrote index.md")

        # 6. Run mkdocs build
        site_path = self._run_mkdocs_build()

        return site_path

    def _embed_mermaid_diagrams(self) -> None:
        """
        Convert standalone .mermaid files into fenced code blocks
        embedded in a new diagram.md file per stage.
        """
        for mermaid_file in self.docs_dir.rglob("*.mermaid"):
            mermaid_content = mermaid_file.read_text()
            stage_name = mermaid_file.parent.name.replace("-", " ").title()

            diagram_md = mermaid_file.parent / "diagram.md"
            diagram_md.write_text(
                f"# {stage_name} — Flow Diagram\n\n"
                f"```mermaid\n{mermaid_content}\n```\n"
            )
            mermaid_file.unlink()  # Remove raw .mermaid file

    def _build_nav(self, journey) -> str:
        """
        Build the nav: section of mkdocs.yml from actual generated files.
        """
        STAGE_SLUG_MAP = {
            "Lead Capture": "01-lead-capture",
            "Application Submission": "02-application",
            "Document Collection": "03-document-collection",
            "KYC & Bureau Verification": "04-kyc-bureau",
            "Financial Analysis & Underwriting": "05-underwriting",
            "Credit Decision": "06-credit-decision",
            "Sanctioning & Offer": "07-sanctioning",
            "Legal Documentation": "08-legal-documentation",
            "Disbursement": "09-disbursement",
            "Post-Disbursal Monitoring": "10-post-disbursal",
            "Collections & Recovery": "11-collections",
            "Loan Closure": "12-loan-closure",
        }

        nav_lines = ["nav:"]
        nav_lines.append("  - Home: index.md")
        nav_lines.append("")

        # Journey section
        nav_lines.append("  - Loan Journey:")
        nav_lines.append("    - Overview: journey/overview.md")

        # Create journey/overview.md as a copy of the main overview
        journey_dir = self.docs_dir / "journey"
        journey_dir.mkdir(exist_ok=True)
        overview_src = self.docs_dir / "00-loan-journey-overview.md"
        if overview_src.exists():
            shutil.copy(overview_src, journey_dir / "overview.md")

        for stage in journey.stages:
            if not stage.components:
                continue
            slug = STAGE_SLUG_MAP.get(stage.stage_name, stage.stage_name.lower().replace(" ", "-"))
            stage_dir = self.docs_dir / slug
            if not stage_dir.exists():
                continue

            nav_lines.append(f"    - '{stage.stage_name}':")
            nav_lines.append(f"      - Overview: {slug}/overview.md")
            if (stage_dir / "components.md").exists():
                nav_lines.append(f"      - Components: {slug}/components.md")
            if (stage_dir / "diagram.md").exists():
                nav_lines.append(f"      - Diagram: {slug}/diagram.md")

        nav_lines.append("")

        # Reference section
        nav_lines.append("  - Reference:")

        ref_files = {
            "hidden-rules-discovered.md": "Hidden Rules",
            "integration-inventory.md": "Integration Inventory",
            "risk-register.md": "Risk Register",
            "00-cross-cutting-components.md": "Cross-Cutting Components",
        }

        # Create reference/ subdirectory with copies
        ref_dir = self.docs_dir / "reference"
        ref_dir.mkdir(exist_ok=True)
        ref_nav_map = {
            "hidden-rules-discovered.md": ("hidden-rules.md", "Hidden Rules"),
            "integration-inventory.md": ("integrations.md", "Integration Inventory"),
            "risk-register.md": ("risk-register.md", "Risk Register"),
            "00-cross-cutting-components.md": ("cross-cutting.md", "Cross-Cutting"),
        }

        for src_name, (dst_name, label) in ref_nav_map.items():
            src = self.docs_dir / src_name
            dst = ref_dir / dst_name
            if src.exists():
                shutil.copy(src, dst)
                nav_lines.append(f"    - '{label}': reference/{dst_name}")

        return "\n".join(nav_lines)

    def _run_mkdocs_build(self) -> Path:
        """
        Run `mkdocs build` to generate the static HTML site.
        Returns path to site/ directory.
        """
        site_path = self.site_root / "site"

        # Check if mkdocs is installed
        if not shutil.which("mkdocs"):
            logger.warning(
                "mkdocs not found in PATH. Skipping HTML build.\n"
                "Install with: pip install mkdocs mkdocs-material pymdown-extensions\n"
                f"Then run: cd {self.site_root} && mkdocs build"
            )
            return site_path

        logger.info(f"  Running: mkdocs build (in {self.site_root})")
        try:
            result = subprocess.run(
                ["mkdocs", "build", "--clean", "--quiet"],
                cwd=str(self.site_root),
                capture_output=True,
                text=True,
                timeout=120,
            )
            if result.returncode == 0:
                logger.info(f"  ✅ MkDocs site built → {site_path}")
            else:
                logger.warning(f"  ⚠️ MkDocs build warnings:\n{result.stderr}")
        except subprocess.TimeoutExpired:
            logger.warning("  MkDocs build timed out")
        except Exception as e:
            logger.warning(f"  MkDocs build error: {e}")

        return site_path

    def serve(self, port: int = 8000) -> None:
        """
        Run `mkdocs serve` for local preview with live reload.
        Blocks until Ctrl+C.
        """
        if not shutil.which("mkdocs"):
            logger.error("mkdocs not installed. Run: pip install mkdocs mkdocs-material")
            return

        print(f"\n🌐 Starting MkDocs server at http://localhost:{port}")
        print("   Press Ctrl+C to stop\n")
        try:
            subprocess.run(
                ["mkdocs", "serve", "--dev-addr", f"localhost:{port}"],
                cwd=str(self.site_root),
            )
        except KeyboardInterrupt:
            print("\nServer stopped.")
